[package]
name = "cryptopals"
version = "0.1.0"
edition = "2021"


[dependencies]
aes = "0.7"
anyhow = "1.0"
base64 = "0.13"
block-modes = "0.8"
hex = "0.4"
plotters = "0.3"
structopt = "0.3"
rand = "0.8"